# Generated by Django 4.0.2 on 2022-03-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('recomNo', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('drCode', models.CharField(max_length=45, null=True)),
                ('drCodeName', models.CharField(max_length=45, null=True)),
                ('recomtitle', models.CharField(max_length=125, null=True)),
                ('recomauthor', models.CharField(max_length=45, null=True)),
                ('recompublisher', models.CharField(max_length=45, null=True)),
                ('recomfilepath', models.TextField(null=True)),
                ('recommokcha', models.TextField(null=True)),
                ('recomcontens', models.TextField(null=True)),
                ('publishYear', models.TextField(null=True)),
                ('recomYear', models.CharField(max_length=45, null=True)),
                ('recomMonth', models.CharField(max_length=45, null=True)),
                ('recomisbn', models.CharField(max_length=45, null=True)),
            ],
        ),
    ]
