# Generated by Django 4.0.3 on 2022-03-11 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recomNo', models.CharField(max_length=45)),
                ('drCode', models.CharField(max_length=45, null=True)),
                ('drCodeName', models.CharField(max_length=45, null=True)),
                ('recomtitle', models.CharField(max_length=125, null=True)),
                ('recomauthor', models.CharField(max_length=45, null=True)),
                ('recompublisher', models.CharField(max_length=45, null=True)),
                ('recomfilepath', models.TextField(null=True)),
                ('recommokcha', models.TextField(null=True)),
                ('recomcontens', models.TextField(null=True)),
                ('publishYear', models.TextField(null=True)),
                ('recomYear', models.CharField(max_length=45, null=True)),
                ('recomMonth', models.CharField(max_length=45, null=True)),
                ('recomisbn', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('recommend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend.recommend')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
