# Generated by Django 4.0.1 on 2022-03-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('lbrry_seq_no', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('lbrry_name', models.CharField(max_length=45)),
                ('gu_code', models.CharField(max_length=10, null=True)),
                ('code_value', models.CharField(max_length=45)),
                ('adres', models.CharField(max_length=45)),
                ('tel_no', models.CharField(max_length=45, null=True)),
                ('hmpg_url', models.CharField(max_length=200, null=True)),
                ('op_time', models.CharField(max_length=200, null=True)),
                ('fdrm_close_date', models.CharField(max_length=200, null=True)),
                ('lbrry_se_name', models.CharField(max_length=45)),
                ('xcnts', models.FloatField(null=True)),
                ('ydnts', models.FloatField(null=True)),
            ],
        ),
    ]
